create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  name varchar(16) not null,
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);
create index if not exists leaderboard_score_idx on public.leaderboard(score desc, created_at asc);
alter table public.leaderboard enable row level security;
-- 前端不直接存取此表；所有讀寫皆由 Netlify Functions 使用 service role 執行。
