const CONFIG={rounds:3,burnGrace:4,maxScore:1000,doneness:[{name:'三分熟',target:6},{name:'五分熟',target:9},{name:'七分熟',target:12},{name:'全熟',target:15}]};
const $=id=>document.getElementById(id);const ui={round:$('round'),score:$('score'),combo:$('combo'),target:$('target'),hint:$('hint'),meat:$('meat'),feedback:$('feedback'),detail:$('detail'),timer:$('timer'),action:$('action'),dialog:$('finishDialog'),finalScore:$('finalScore'),form:$('finishForm'),name:$('playerName'),status:$('saveStatus'),again:$('again'),list:$('leaderboard'),refresh:$('refresh')};
let state={round:0,score:0,combo:0,active:false,start:0,timerId:null,current:null,results:[],submitted:false};
function randomTarget(){return CONFIG.doneness[Math.floor(Math.random()*CONFIG.doneness.length)]}function resetMeat(){ui.meat.className='meat raw';document.querySelector('.grill-scene').classList.remove('active')}
function startGame(){state={round:0,score:0,combo:0,active:false,start:0,timerId:null,current:null,results:[],submitted:false};ui.score.textContent='0';ui.combo.textContent='×0';ui.round.textContent=`0 / ${CONFIG.rounds}`;ui.target.textContent='準備開烤';ui.hint.textContent=`每局 ${CONFIG.rounds} 片肉，越接近指定熟度越高分。`;ui.feedback.textContent='準備好了嗎？';ui.detail.textContent='按下開始遊戲';ui.timer.textContent='0.00 秒';ui.name.value='';ui.status.textContent='';ui.dialog.close?.();nextRound()}
function nextRound(){if(state.round>=CONFIG.rounds)return finishGame();state.round++;state.current=randomTarget();state.active=false;resetMeat();ui.round.textContent=`${state.round} / ${CONFIG.rounds}`;ui.target.textContent=state.current.name;ui.hint.textContent=`理想時間 ${state.current.target} 秒`;ui.feedback.textContent='準備放肉';ui.detail.textContent='按下「放上烤肉」開始計時';ui.timer.textContent='0.00 秒';ui.action.textContent='🥩 放上烤肉';ui.action.onclick=startCooking}
function startCooking(){state.active=true;state.start=performance.now();ui.meat.className='meat cooking';document.querySelector('.grill-scene').classList.add('active');ui.feedback.textContent='滋滋滋…';ui.detail.textContent='看準時間，起鍋！';ui.action.textContent='🔥 起鍋！';ui.action.onclick=stopCooking;tick()}
function tick(){if(!state.active)return;const sec=(performance.now()-state.start)/1000;ui.timer.textContent=`${sec.toFixed(2)} 秒`;if(sec>=state.current.target*.72)ui.meat.className='meat good';if(sec>=state.current.target+CONFIG.burnGrace)ui.meat.className='meat burnt';state.timerId=requestAnimationFrame(tick)}
function stopCooking(){if(!state.active)return;state.active=false;cancelAnimationFrame(state.timerId);const elapsed=(performance.now()-state.start)/1000;const diff=Math.abs(elapsed-state.current.target);let points=Math.max(0,Math.round(CONFIG.maxScore-diff*300));const burnt=elapsed>=state.current.target+CONFIG.burnGrace;if(burnt)points=0;let grade;if(burnt)grade=['💀 烤焦了！','這片只能跟炭作伴了'];else if(diff<=.1)grade=['👑 PERFECT！','神級火候'];else if(diff<=.3)grade=['🔥 AMAZING！','非常接近完美'];else if(diff<=.6)grade=['✨ GREAT！','烤得漂亮'];else if(diff<=1)grade=['👍 GOOD','還不錯'];else if(elapsed<state.current.target)grade=['🥩 太生了','再烤一下會更好'];else grade=['😵 太熟了','下次早點起鍋'];if(diff<=.6&&!burnt)state.combo++;else state.combo=0;const comboBonus=state.combo>=2?Math.min(200,(state.combo-1)*40):0;points+=comboBonus;state.score+=points;state.results.push({target:state.current.target,elapsed:Number(elapsed.toFixed(3)),points});ui.score.textContent=state.score.toLocaleString();ui.combo.textContent=`×${state.combo}`;ui.feedback.textContent=grade[0];ui.detail.textContent=`${grade[1]}｜誤差 ${diff.toFixed(2)} 秒｜+${points}${comboBonus?`（Combo +${comboBonus}）`:''}`;ui.timer.textContent=`${elapsed.toFixed(2)} 秒`;ui.action.textContent=state.round===CONFIG.rounds?'查看成績':'下一片肉 →';ui.action.onclick=nextRound}
function finishGame(){resetMeat();ui.finalScore.textContent=state.score.toLocaleString();ui.status.textContent='';ui.dialog.showModal()}
async function loadLeaderboard(){ui.list.innerHTML='<li class="empty">讀取排行榜中…</li>';try{const r=await fetch('/.netlify/functions/leaderboard');if(!r.ok)throw new Error();const rows=await r.json();if(!rows.length){ui.list.innerHTML='<li class="empty">目前還沒有成績，來搶第一名！</li>';return}ui.list.innerHTML=rows.map((x,i)=>`<li><span class="rank">${i+1}</span><span class="player"></span><span class="points">${Number(x.score).toLocaleString()}</span></li>`).join('');[...ui.list.querySelectorAll('.player')].forEach((el,i)=>el.textContent=rows[i].name)}catch{ui.list.innerHTML='<li class="empty">排行榜暫時無法讀取</li>'}}
ui.form.addEventListener('submit',async e=>{e.preventDefault();if(state.submitted)return;const name=ui.name.value.trim();if(!name)return;const submitButton=ui.form.querySelector('button[type="submit"]');state.submitted=true;submitButton.disabled=true;ui.status.textContent='送出中…';try{const r=await fetch('/.netlify/functions/submit-score',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,results:state.results})});const data=await r.json();if(!r.ok)throw new Error(data.error||'送出失敗');await loadLeaderboard();ui.dialog.close();ui.action.textContent='再玩一次';ui.action.onclick=startGame;ui.target.textContent=data.ranked?'🎉 成功進入 TOP 10！':'本局完成';ui.hint.textContent=data.ranked?`${name}｜${Number(data.score).toLocaleString()} 分`:`${Number(data.score).toLocaleString()} 分｜未進入 TOP 10`;ui.feedback.textContent='烤肉完成！';ui.detail.textContent='按下「再玩一次」開始新的一局'}catch(err){state.submitted=false;submitButton.disabled=false;ui.status.textContent=`⚠️ ${err.message}`}});ui.dialog.addEventListener('close',()=>{const submitButton=ui.form.querySelector('button[type="submit"]');if(submitButton)submitButton.disabled=false});ui.again.onclick=()=>{ui.dialog.close();startGame()};ui.refresh.onclick=loadLeaderboard;ui.action.onclick=startGame;loadLeaderboard();